language: java

jdk:
  - oraclejdk8

sudo: false

services:
  - docker
  
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  
cache:
  directories:
    - $HOME/.m2
