mongo:
  image: mongo:latest
  ports:
   - 27017:27017
docker-rest-service:
  image: zachariahyoung/docker-rest
  ports:
   - 8080:8080
  links:
   - mongo
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
