spring.profiles.active: development
---
spring:
  profiles: development
  data:
    mongodb:
      host: 192.168.99.100
      port: 27017
---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongo
      port: 27017
